<?php

namespace ContainerJeMJAKZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LjKqQhCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ljKqQhC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ljKqQhC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\MainController::Main' => ['privates', '.service_locator.brzH9uj.App\\Controller\\MainController::Main()', 'getMainControllerMainService', true],
            'App\\Controller\\UtilitiesController::getCollection' => ['privates', '.service_locator.brzH9uj.App\\Controller\\UtilitiesController::getCollection()', 'getUtilitiesControllergetCollectionService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\MainController:Main' => ['privates', '.service_locator.brzH9uj.App\\Controller\\MainController::Main()', 'getMainControllerMainService', true],
            'App\\Controller\\UtilitiesController:getCollection' => ['privates', '.service_locator.brzH9uj.App\\Controller\\UtilitiesController::getCollection()', 'getUtilitiesControllergetCollectionService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\MainController::Main' => '?',
            'App\\Controller\\UtilitiesController::getCollection' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\MainController:Main' => '?',
            'App\\Controller\\UtilitiesController:getCollection' => '?',
        ]);
    }
}
