<?php

namespace Container8eLAd48;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranslatorInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fdTWzgN.Symfony\Contracts\Translation\TranslatorInterface' shared service.
     *
     * @return \Symfony\Contracts\Translation\TranslatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fdTWzgN": it references interface "Symfony\\Contracts\\Translation\\TranslatorInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
