<?php

namespace Container7y9ufn1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FdTWzgNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fdTWzgN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fdTWzgN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'translator' => ['privates', '.errored..service_locator.fdTWzgN.Symfony\\Contracts\\Translation\\TranslatorInterface', NULL, 'Cannot autowire service ".service_locator.fdTWzgN": it references interface "Symfony\\Contracts\\Translation\\TranslatorInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'translator' => 'Symfony\\Contracts\\Translation\\TranslatorInterface',
        ]);
    }
}
