<?php

namespace ContainerXNtvOth;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMainControllerMainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BPlWP47.App\Controller\MainController::Main()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BPlWP47.App\\Controller\\MainController::Main()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\UtilitiesRepository', 'getUtilitiesRepositoryService', true],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'repository' => 'App\\Repository\\UtilitiesRepository',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\MainController::Main()', $container);
    }
}
