<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXNtvOth\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXNtvOth/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXNtvOth.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXNtvOth\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXNtvOth\App_KernelDevDebugContainer([
    'container.build_hash' => 'XNtvOth',
    'container.build_id' => 'b43e99ea',
    'container.build_time' => 1730985052,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXNtvOth');
