<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEmR39vo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEmR39vo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEmR39vo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEmR39vo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEmR39vo\App_KernelDevDebugContainer([
    'container.build_hash' => 'EmR39vo',
    'container.build_id' => '5739d6b9',
    'container.build_time' => 1731322717,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEmR39vo');
